version: '3.1'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=beingzeromaster
    volumes:
      - './redis-server/data:/bitnami'

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6378:6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=beingzeromaster
      - REDIS_PASSWORD=beingzeroreplica
  
  memcached:
    image: 'bitnami/memcached:latest'
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_USERNAME=root
      - MEMCACHED_PASSWORD=beingzero
    restart: always
    ports:
    - '11211:11211'
    networks:
    - beingzero

networks:
  beingzero: